name: Welcome New Issues

on:
  issues:
    types: [opened]

jobs:
  welcome-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Needed to post a comment on the issue

    steps:
      - name: Add welcome comment
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.payload.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const message = `
👋 Hi @${context.payload.issue.user.login}!

Thanks for opening this issue — we really appreciate your contribution!  
Our team will take a look as soon as possible. In the meantime, feel free to share more details or context if you have any.

Happy contributing! 🚀
`;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: issueNumber,
              body: message
            });
